const CustomError = require("../extensions/custom-error");

const chainMaker = {
  getLength() {
    'THROWN'
    // remove line with error and write your code here
  },
  addLink(value) {
    'THROWN';
    // remove line with error and write your code here
  },
  removeLink(position) {
    'THROWN';
    // remove line with error and write your code here
  },
  reverseChain() {
    'THROWN';
    // remove line with error and write your code here
  },
  finishChain() {
    'THROWN';
    // remove line with error and write your code here
  }
};

module.exports = chainMaker;
